string(REPLACE "|" ";" RENAME_GLOB "*cc|*cc-*|*++|*++-*|*cpp|*-gfortran|*-gdc")
list(TRANSFORM RENAME_GLOB PREPEND "${BINDIR}/${GNU_TARGET_NAME}-")
file(GLOB BINARIES RELATIVE ${BINDIR} ${RENAME_GLOB})
message(${BINDIR})

foreach (BINARY ${BINARIES})
    if (${BINARY} MATCHES ".*\\.br_real")
        continue()
    endif ()
    if (${BINARY} MATCHES "(-ar)|(-ranlib)|(-nm)$")
        continue()
    endif ()
    if (${BINARY} MATCHES "^(.*cc)|(.*cc\\-.*)|(.*\\+\\+)|(.*\\+\\+\\-.*)|(.*cpp)|(.*\\-gfortran)|(.*\\-gdc)$")
        file(RENAME ${BINDIR}/${BINARY} ${BINDIR}/${BINARY}.br_real)
    endif ()
endforeach ()