file(GLOB BINARIES RELATIVE ${SOURCE} "${SOURCE}/${GNU_TARGET_NAME}-*")

foreach (BINARY ${BINARIES})
    if (${BINARY} MATCHES ".*\\.br_real")
        continue()
    elseif (${BINARY} MATCHES "(-ar)|(-ranlib)|(-nm)$")
        file(INSTALL ${SOURCE}/${BINARY} DESTINATION ${DESTINATION} USE_SOURCE_PERMISSIONS)
    elseif (${BINARY} MATCHES "^(.*cc)|(.*cc\\-.*)|(.*\\+\\+)|(.*\\+\\+\\-.*)|(.*cpp)|(.*\\-gfortran)|(.*\\-gdc)$")
        file(COPY_FILE ${SOURCE}/${BINARY} "${DESTINATION}/${BINARY}.br_real")
    else ()
        file(INSTALL ${SOURCE}/${BINARY} DESTINATION ${DESTINATION} USE_SOURCE_PERMISSIONS)
    endif ()
endforeach ()