file(GLOB BINARIES RELATIVE ${BINDIR} "${BINDIR}/${GNU_TARGET_NAME}-*")

foreach (BINARY ${BINARIES})
    if (${BINARY} MATCHES ".*\\.br_real")
        continue()
    elseif (${BINARY} MATCHES "(-ar)|(-ranlib)|(-nm)|(-c\\+\\+filt)$")
        continue()
    elseif (${BINARY} MATCHES "^(.*cc)|(.*cc\\-.*)|(.*\\+\\+)|(.*\\+\\+\\-.*)|(.*cpp)|(.*\\-gfortran)|(.*\\-gdc)$")
        file(RENAME "${BINDIR}/${BINARY}" "${BINDIR}/${BINARY}.br_real")
        file(CREATE_LINK "toolchain-wrapper" "${BINDIR}/${BINARY}" SYMBOLIC)
    endif ()
endforeach ()